services:
  gateway:
    container_name: apigateway
    build: ./apigateway
    volumes:
      - ./apigateway/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3010:3010"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  microservice:
    container_name: microservice
    build: ./microservice
    volumes:
      - ./microservice/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3011:3011"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

  appliance:
    container_name: appliance
    build: ./appliance
    volumes:
      - ./appliance/code:/usr/src/app
    networks:
      - msexample
    ports:
      - "3012:3012"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"

networks:
  msexample:
    driver: bridge