name: Backend Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test-backend:
    name: Lint and Test Backend Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd apigateway/code && npm install
          cd ../../microservice/code && npm install

      # Step 4: Lint controllers, middleware, and routes
      - name: Lint apigateway directories
        working-directory: apigateway/code
        run: |
          npx eslint controllers/**/*.js
          npx eslint middleware/**/*.js
          npx eslint routes/**/*.js

      - name: Lint microservice directories
        working-directory: microservice/code
        run: |
          npx eslint controllers/**/*.js
          npx eslint middleware/**/*.js
          npx eslint routes/**/*.js

      # Step 5: Run tests for apigateway and microservice
      - name: Run tests for apigateway
        working-directory: apigateway/code
        run: npm test

      - name: Run tests for microservice
        working-directory: microservice/code
        run: npm test

      # Step 6: Success message
      - name: Log success message
        if: success()
        run: echo "✅ Linting and tests completed successfully!"

      # Step 7: Failure notification
      - name: Log failure message
        if: failure()
        run: echo "❌ Linting or tests failed. Please check the logs."
