name: Backend Pipeline

on:
  push:
    branches:
      - main
      - backendtests
  pull_request:
    branches:
      - main
      - backendtests

jobs:
  backend-pipeline:
    name: Backend Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies for apigateway
      - name: Install dependencies for apigateway
        working-directory: apigateway/code
        run: npm install

      # Step 3: Install dependencies for microservice
      - name: Install dependencies for microservice
        working-directory: microservice/code
        run: npm install

      # Step 4: Log success message
      - name: Log success message
        run: echo "✅ Backend pipeline ran successfully for both apigateway and microservice."
